DealDash.Web/ViewModels/AuctionViewModels.cs
using DealDash.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DealDash.Web.ViewModels
{
    public class AuctionsListingViewModel : PageViewModel
    {
        public int? pageNO { get; set; }
        public List<Category> Categories { get; set; }
        public List<Auction> Auctions { get; set; }
        public int? CategoryID { get; set; }
        public string searchTerm { get; set; }
       
        public Pager Pager { get; set; }

    }
    public class AuctionViewModel:PageViewModel
    {
        public List<Auction> AllAuctions { get; set; }
        public List<Auction> PromotedAuctions { get; set; }
    }

    public class AuctionDetailViewModel : PageViewModel
    {
        public Auction Auction { get; set; }
    }

    public class CreateAuctionViewModel : PageViewModel
    {
        public int CategoryID { get; set; }
        [Required]
        [MinLength(4, ErrorMessage = "Minimum length should be 4")]
        [MaxLength(8, ErrorMessage = ("Max should be 8"))]
        public string Title { get; set; }

        public string Description { get; set; }
        [Range(5, 1000000, ErrorMessage = "Range between 5 and 1000000")]
        public decimal ActualAmount { get; set; }
        public DateTime? StartingTime { get; set; }
        public DateTime? EndingTime { get; set; }
        public string AuctionPictures { get; set; }
        public List<Category> Categories { get; set; }
        public int ID { get; set; }
        public List<AuctionPicture> AuctionPicturesList { get; set; }
    }
}

DealDash.Web/Controllers/AuctionController.cs
using DealDash.Entities;
using DealDash.Services;
using DealDash.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DealDash.Web.Controllers
{
    public class AuctionController : Controller
    {
        // GET: Auction
        public ActionResult Index(int? categoryID, string searchTerm, int? pageNO)
        {
            AuctionsListingViewModel model = new AuctionsListingViewModel();
            model.PageTitle = "Auctions";
            model.PageDescription = "This is Auctions Page";
            model.CategoryID = categoryID;
            model.searchTerm = searchTerm;
            model.pageNO = pageNO;
            model.Categories = CategoriesService.Instance.GetAllCategory();

           return View(model);
                 
        }
        // GET: Auction
        public ActionResult Listing(int?categoryID,string searchTerm,int?pageNO)
        {
            AuctionsListingViewModel model = new AuctionsListingViewModel();
            //  model.pageNO = pageNO ?? 1;
            var pageSize = 2;
            model.Auctions = AuctionService.Instance.SearchAuction(categoryID,searchTerm,pageNO, pageSize);
            int totalcount = AuctionService.Instance.getAuctionCount(categoryID, searchTerm);
            model.Pager = new Pager(totalcount, pageNO, pageSize);
            
           return PartialView(model);
            
          
        }

        public ActionResult Create()
        {
            CreateAuctionViewModel model = new CreateAuctionViewModel();
            model.Categories = CategoriesService.Instance.GetAllCategory();
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Create(CreateAuctionViewModel model)
        {
            JsonResult result = new JsonResult();
            if (ModelState.IsValid)
            {
                Auction auction = new Auction();
                auction.CategoryID = model.CategoryID;
                auction.Title = model.Title;
                auction.Description = model.Description;
                auction.ActualAmount = model.ActualAmount;
                auction.StartingTime = model.StartingTime;
                auction.EndingTime = model.EndingTime;
                //check if we have auctionpicid posted back from form
                if (!string.IsNullOrEmpty(model.AuctionPictures))
                {
                    var PicIDS = model.AuctionPictures.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(ID => int.Parse(ID)).ToList();

                    auction.AuctionPictures = new List<AuctionPicture>();
                    auction.AuctionPictures.AddRange(PicIDS.Select(x => new AuctionPicture() { PictureID = x }).ToList());//to save in auctionpicture table with auction id and pic id

                }   //foreach (var picID in PicIDS)
                    //{
                    //    var auctionpic = new AuctionPicture();
                    //    auctionpic.PictureID = picID;«
                    //    auction.AuctionPictures.Add(auctionpic);
                    //}

                AuctionService.Instance.SaveAuction(auction);
                result.Data = new { success = true };
            }
            else
            {
                result.Data = new { success = false, Error = "Please Enter Valid Value" };
            }
            return result;
        }

        public ActionResult Edit(int ID)
        {
            CreateAuctionViewModel model = new CreateAuctionViewModel();
       
            var auction = AuctionService.Instance.AuctionGetById(ID);
            model.ID = auction.ID;
            model.Title = auction.Title;
            model.CategoryID = auction.CategoryID;
            model.Description = auction.Description;
            model.ActualAmount = auction.ActualAmount;
            model.StartingTime = auction.StartingTime;
            model.EndingTime = auction.EndingTime;
            model.AuctionPicturesList = auction.AuctionPictures;

            model.Categories = CategoriesService.Instance.GetAllCategory();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(CreateAuctionViewModel model)
        {
            Auction auction =new Auction();
            auction.ID = model.ID;
            auction.CategoryID = model.CategoryID;
            auction.Title = model.Title;
            auction.Description = model.Description;
            auction.ActualAmount = model.ActualAmount;
            auction.StartingTime = model.StartingTime;
            auction.EndingTime = model.EndingTime;
            if (!string.IsNullOrEmpty(model.AuctionPictures))
            {
                var PicIDS = model.AuctionPictures.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(ID => int.Parse(ID)).ToList();

                auction.AuctionPictures = new List<AuctionPicture>();
                auction.AuctionPictures.AddRange(PicIDS.Select(x => new AuctionPicture() {AuctionID=auction.ID, PictureID = x }).ToList());//to save in auctionpicture table with auction id and pic id

            }

            AuctionService.Instance.UpdateAuction(auction);
            return RedirectToAction("Listing");
         
        }

        public ActionResult Delete(int ID)
        {
            var model = AuctionService.Instance.AuctionGetById(ID);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Delete(Auction auction)
        {
            AuctionService.Instance.AuctionDelete(auction);
            return RedirectToAction("Listing");
        }

        
        public ActionResult Details(int id)
        {
            AuctionDetailViewModel model = new AuctionDetailViewModel();
             model.Auction = AuctionService.Instance.AuctionGetById(id);
            model.PageTitle = "Auction Detail" + model.Auction.Title;
            model.PageDescription = model.Auction.Description.Substring(0,10);

            return View(model);
        }
    }
}

DealDash.Web/Controllers/SharedController.cs
using DealDash.Entities;
using DealDash.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DealDash.Web.Controllers
{
    public class SharedController : Controller
    {
        [HttpPost]
        public JsonResult UploadPicture()
        {
            JsonResult json = new JsonResult();
            List<object> picturejson = new List<object>();
            var pictures = Request.Files;
            for (int i = 0; i < pictures.Count; i++)
            {
                var picture = pictures[i];
                var filename =Guid.NewGuid()+ Path.GetExtension(picture.FileName);
                var path = Server.MapPath("~/Content/images/") + filename;
                picture.SaveAs(path);

                var dbpicture = new Picture();//we need url back to see in div
                dbpicture.URL = filename;//to save in picture table
                int picID = SharedService.Instance.SaveAuctionPic(dbpicture);//id return

                picturejson.Add(new { ID = picID, pictureurl = filename });//retrn the picIDs and url to see pic in div
            }
            json.Data = picturejson;//return all ids and url of all pic
            return json;
        }
    }
}

DealDash.Web/Views/Auction/Create.cshtml
@model CreateAuctionViewModel

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle">Create Record</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="createForm" method="post">
        <div class="form-group">
            <label>Category</label>
            <select class="form-control" name="CategoryID">
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.ID">@category.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label>Title</label>
            <input class="form-control" name="Title" />
        </div>
       <div class="form-group">
           <label>Description</label>
           <input class="form-control" name="Description" />
       </div>
       <div class="form-group">
           <label>ActualAmount</label>
           <input class="form-control" name="ActualAmount" />
       </div>
       <div class="form-group">
           <label>StartingTime</label>
           <input class="form-control" name="StartingTime" />
       </div>
       <div class="form-group">
           <label>EndingTime</label> 
           <input class="form-control" name="EndingTime" />
       </div>
        <div class="form-group">
            <label>Select Pictures</label>
            <input id="auctionPictures" class="form-control" name="AuctionPictures" type="file" multiple />
            <div id="picturearea">

            </div>
            <input type="hidden" name="AuctionPictures" id="pictureIDs" />
        </div>
        <div id="formError" class="form-group bg-danger" style="display:none;">
        </div>
        
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary" id="btnsave">Save changes</button>
</div>

<script>
    $("#auctionPictures").change(function () {
      
        var pictures = this.files;

        var picsData = new FormData();

        for (var i = 0; i < pictures.length; i++) {
            picsData.append("Picture", pictures[i])
        }

        $.ajax({
            
            url: '@Url.Action("UploadPicture", "Shared")',
            type: "post",
            data: picsData,
            datatype: "json",
            processData: false,
            contentType: false
            
		})
            .done(function (responses) {
                //var picIDs = '';
                for (var i = 0; i < responses.length; i++) {
                    var picResponese = responses[i];
                    AttachNewImage(picResponese.pictureurl, picResponese.ID);

                    //var imghtml = "<img class='img-fluid' src='/content/images/" + picResponese.pictureurl + "'>";

                    //picIDs = picIDs + "," + picResponese.ID;
                }
                //$("#pictureIDs").val(picIDs);
        })
    });
    function AttachNewImage(imageURL,imageID) {
       
        var $newimgHTML = $("#imageTemplate").clone();
        $newimgHTML.find(".image").attr("src", "/content/images/" + imageURL);
        $newimgHTML.find(".image").attr("data-id",imageID);
        $("#picturearea").append($newimgHTML.html());
        RemoveImageOnClick();
    }
    $("#createForm").validate({
        rules: {
            Title: {
                required: true,
                minlength: 4,
                maxlength:8
            }
        },
        messages: {
            Title: {
                required: "Title is required",
                minlength: "Min is 4",
                maxlength: "Max is 8"
            }
          
        }
    });
    $("#btnsave").click(function () {
        if ($("#createForm").valid())
        {

   
        var imageids = [];
        $("#picturearea .image").each(function () {
            var imageid = $(this).attr("data-id");
            imageids.push(imageid);
        });
        $("#pictureIDs").val(imageids.join());

        $.ajax({
            url: '@Url.Action("Create", "Auction")',
            type: "post",
            data: $("#createForm").serialize()

        })
            .done(function (response) {
                if (response.success) {
                    ReloadListing();
                    $('#ShowHideModal').modal('toggle');
                }
                else {
                    $("#formError").html(response.Error);
                    $("#formError").show();
                }


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    }
    });
</script>

DealDash.Web/Views/Auction/Delete.cshtml
@model Auction
@{
    ViewBag.Title = "Delete";
}
<h1>are  you sure you wna tto delete?</h1>
<h2>Delete</h2>
<form method="post">
    <input type="hidden" value="@Model.ID" />
    
    <button type="button" id="btndelete">
        Yes
    </button>
    <a href="@Url.Action("Index","Auction")" class="btn btn-success" >No</a>

    
</form>
@*<script>
    $("#btndelete").click(function () {
		$.ajax({
            url: '@Url.Action("Delete", "Auction")',
            method:"post"

		})
            .done(function (response) {

                $("#listingArea").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});
</script>*@

DealDash.Web/Views/Auction/Details.cshtml
@model AuctionDetailViewModel
<div class="row">
 
    <div class="col-lg-12">
       
        <div class="card mt-4">
            @if (Model.Auction.AuctionPictures != null && Model.Auction.AuctionPictures.Count > 0)
            {
                var firstauctionPicture = Model.Auction.AuctionPictures.First();
                var i = 0;
                <div id="carouselIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">

                        @foreach (var picture in Model.Auction.AuctionPictures)
                        {
                            var active = picture == firstauctionPicture ? "active" : string.Empty;
                            <li class="@active" data-target="#carouselIndicators" data-slide-to="@i"></li>
                            i++;
                        }

                    </ol>
                    <div class="carousel-inner" role="listbox">
                        @foreach (var auctionpicture in Model.Auction.AuctionPictures)
                {
                    var active = auctionpicture == firstauctionPicture ? "active" : string.Empty;
                    var picurl = "/Content/images/" + auctionpicture.Pictures.URL;
                            <div class="carousel-item @active">
                                <img class="d-block img-fluid" src="@picurl" alt="First slide">
                            </div>
                        }


                    </div>
                    <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            }
            <div class="card-body">
                <h3 class="card-title">@Model.Auction.Title</h3>
                <h4>@Model.Auction.ActualAmount</h4>
                <p class="card-text">@Model.Auction.Description</p>
                <span class="text-warning">★ ★ ★ ★ ☆</span>
                4.0 stars
            </div>
        </div>
        <!-- /.card -->

        <div class="card card-outline-secondary my-4">
            <div class="card-header">
                Product Reviews
            </div>
            <div class="card-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <a href="#" class="btn btn-success">Leave a Review</a>
            </div>
        </div>
        <!-- /.card -->

    </div>
    <!-- /.col-lg-9 -->

</div>

DealDash.Web/Views/Auction/Edit.cshtml
@model CreateAuctionViewModel
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle">Edit Record</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="editForm" method="post">
        <div class="form-group">
            <input type="hidden" name="ID" value="@Model.ID" />
            <label>Category</label>
           
            <select class="form-control" name="CategoryID">
                @foreach (var category in Model.Categories)
                {
                    var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                    <option value="@category.ID" @selected>@category.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
           
            <label>Title</label>
            <input class="form-control" name="Title" value="@Model.Title" />
        </div>
        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="Description" value="@Model.Description" />
        </div>
        <div class="form-group">
            <label>ActualAmount</label>
            <input class="form-control" name="ActualAmount" value="@Model.ActualAmount" />
        </div>
        <div class="form-group">
            <label>StartingTime</label>
            <input class="form-control" name="StartingTime" value="@Model.StartingTime" />
        </div>
        <div class="form-group">
            <label>EndingTime</label>
            <input class="form-control" name="EndingTime" value="@Model.EndingTime" />
        </div>
        <div class="form-group">
            <label>Select Pictures</label>
            <input id="auctionPictures" class="form-control" name="AuctionPictures" type="file" multiple />
            <div id="picturearea" class="mt-2">
                @if (Model.AuctionPicturesList != null && Model.AuctionPicturesList.Count > 0)
                {
                    foreach (var picture in Model.AuctionPicturesList)
                    {
                        <img class='image img-thumbnail' src='~/Content/images/@picture.Pictures.URL' data-id="@picture.ID" style="width:200px;height:200px;" />
                    }

                }
            </div>
            <input type="hidden" name="AuctionPictures" id="pictureIDs" />
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary" id="btnEdit">Save changes</button>
</div>
    <script>
        RemoveImageOnClick();
        $("#btnEdit").click(function () {
            var imageids = [];
            $("#picturearea .image").each(function () {
                var imageid = $(this).attr("data-id");
                imageids.push(imageid);
            });
            $("#pictureIDs").val(imageids.join());

            $.ajax({
                url: '@Url.Action("Edit", "Auction")',
            method:"post",
            data: $("#editForm").serialize()

		})
            .done(function (response) {
                $('#ShowHideModal').modal('toggle');
                $("#listingArea").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
        });
          $("#auctionPictures").change(function () {

        var pictures = this.files;

        var picsData = new FormData();

        for (var i = 0; i < pictures.length; i++) {
            picsData.append("Picture", pictures[i])
        }

        $.ajax({

            url: '@Url.Action("UploadPicture", "Shared")',
            type: "post",
            data: picsData,
            datatype: "json",
            processData: false,
            contentType: false

		})
            .done(function (responses) {
                //var picIDs = '';
                for (var i = 0; i < responses.length; i++) {
                    var picResponese = responses[i];
                    AttachNewImage(picResponese.pictureurl, picResponese.ID);

                    //var imghtml = "<img class='img-fluid' src='/content/images/" + picResponese.pictureurl + "'>";

                    //picIDs = picIDs + "," + picResponese.ID;
                }
                //$("#pictureIDs").val(picIDs);
        })
    });
    </script>

DealDash.Web/Views/Auction/Index.cshtml
@model AuctionsListingViewModel
@{
    var categoryID = Model.CategoryID.HasValue ? Model.CategoryID.Value : 0;
}
<div class="row">
    <div class="col-lg-12 m-2">
        <form method="post">
            <div class="form-row align-items-center">
                <div class="col-auto my-1">
                    <select class="custom-select mr-sm-2" name="categoryID">
                        <option>Select Category</option>
                        @foreach (var category in Model.Categories)
                        {
                            var selected = category.ID == categoryID ? "selected" : string.Empty;
                            <option @selected value="@category.ID">@category.Name</option>
                        }
                    </select>
                </div>
                <div class="col-auto my-1">
                    <div class="custom-control custom-checkbox mr-sm-2">
                        <input  name="searchTerm" value="@Model.searchTerm" type="text" class="form-control" placeholder="Search" />
                    </div>

                </div>
                <div class="col-auto my-1">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>

        </form>
      
        <div class="float-right">
            <button id="btnnew" class="btn btn-primary "> New</button>
        </div>
      <div  id="listingArea">
          @{Html.RenderAction("Listing",new { categoryID=Model.CategoryID ,searchTerm=Model.searchTerm, pageNO=Model.pageNO });}
      </div>
      
        <!-- Modal -->
        <div class="modal fade" id="ShowHideModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" id="ModalContainer">

                </div>
            </div>
        </div>
        <div id="imageTemplate" style="display:none;">
            <img class='image img-thumbnail' src='' style="width:200px;height:200px;" />
        </div>
        <script>

            $("#btnnew").click(function () {
                $.ajax({
                    url: '@Url.Action("Create", "Auction")',
		})
                .done(function (response) {
                    $('#ShowHideModal').modal('toggle');
            $("#ModalContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
            });

            function RemoveImageOnClick() {
                $("#picturearea .image").click(function () {
                    $(this).remove();
                });
            }

            function AttachNewImage(imageURL, imageID) {

                var $newimgHTML = $("#imageTemplate").clone();
                $newimgHTML.find(".image").attr("src", "/content/images/" + imageURL);
                $newimgHTML.find(".image").attr("data-id", imageID);
                $("#picturearea").append($newimgHTML.html());
                RemoveImageOnClick();
            }
            function ReloadListing() {
                $.ajax({
                url: '@Url.Action("Listing", "Auction")',
		})
                    .done(function (response) {
                        $("#listingArea").html(response);
        })
            }
        </script>
    </div>

</div>

DealDash.Web/Views/Auction/Listing.cshtml
@model AuctionsListingViewModel

<table class="table table-hover">
    <thead>
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Description</th>
            <th>Actual Amount</th>
            <th>Starting Time</th>
            <th>Ending Time</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        @if (Model.Auctions != null && Model.Auctions.Count > 0)
        {
            foreach (var aucation in Model.Auctions)
            {
                <tr>

                    <td>
                        <input type="hidden" value="@aucation.ID" />
                        @aucation.Title
                    </td>
                    <td>@aucation.Category.Name</td>
                    <td>@aucation.Description</td>
                    <td>@aucation.ActualAmount</td>
                    <td>@aucation.StartingTime</td>
                    <td>@aucation.EndingTime</td>
                    <td>
                        <button class="btnedit" data-id="@aucation.ID">Edit</button>
                        <button class="btndelete" data-id="@aucation.ID">Delete</button>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr  >
                <td class="text-center" colspan="7">No Record!!</td>
            </tr>
        }

    </tbody>
</table>
@if (Model.Pager != null && Model.Pager.TotalPages > 1)
{
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            
                @if (Model.Pager.CurrentPage == 1)
                {
                 <li class="page-item disabled">
                <a class="page-link" href="#">Previous</a>
                </li>   
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index","Auction",new {pageNO=Model.Pager.CurrentPage-1, categoryID = Model.CategoryID,searchTerm=Model.searchTerm})">Previous</a>

                    </li>

                }

                @for (int page = Model.Pager.CurrentPage; page < Model.Pager.EndPage + 1; page++)
                {
                    var active = page == Model.Pager.CurrentPage ? "active" : string.Empty;
                    <li class="page-item @active"><a class="page-link" href="@Url.Action("Index","Auction",new {pageNO=page, categoryID = Model.CategoryID,searchTerm=Model.searchTerm })">@page</a></li>

                }
            @if (Model.Pager.CurrentPage == Model.Pager.EndPage)
            {
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Index","Auction",new {pageNO=Model.Pager.CurrentPage+1, categoryID = Model.CategoryID,searchTerm=Model.searchTerm})">Next</a>
                </li>
            }
           
        </ul>
    </nav>
}

<script>

    $(".btnedit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Auction")',
			data: {
                ID: $(this).attr("data-id")
			}
		})
            .done(function (response) {
                $('#ShowHideModal').modal('toggle');
                $("#ModalContainer").html(response);

        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
        $(".btndelete").click(function () {
            var result = confirm("Are Sure You want to delete this");

            if (result)
            {
                $.ajax({
                    url: '@Url.Action("Delete", "Auction")',
                    method:"post",
			data: {
                ID: $(this).attr("data-id")
			}
		})
                    .done(function (response) {

            $("#listingArea").html(response);

        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
            }

	});
</script>