DealDash.Web/ViewModels/CategoriesViewModels.cs
using DealDash.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DealDash.Web.ViewModels
{
    public class CategoriesListingViewModel : PageViewModel
    {
        public List<Category> Categories { get; set; }
        
    }
    public class CategoriesViewModel : PageViewModel
    {
        public List<Category> AllCategories { get; set; }
        public List<Category> PromotedCategories { get; set; }
    }

    public class CategoriesDetailViewModel : PageViewModel
    {
        public Category Categories { get; set; }
    }

    public class CategoryViewModel : PageViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<Auction> Auctions{ get; set; }


    }
}

DealDash.Web/Controllers/CategoriesController.cs
using DealDash.Entities;
using DealDash.Services;
using DealDash.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DealDash.Web.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Auction
        public ActionResult Index()
        {
            CategoriesListingViewModel model = new CategoriesListingViewModel();
            model.PageTitle = "Category";
            model.PageDescription = "This is Category Page";           
           return View(model);
                 
        }
        // GET: Auction
        public ActionResult Listing()
        {
            CategoriesListingViewModel model = new CategoriesListingViewModel();
            model.Categories = CategoriesService.Instance.GetAllCategory();
            return PartialView(model);
            
          
        }

        public ActionResult Create()
        {
            CategoryViewModel model = new CategoryViewModel();
            
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(CategoryViewModel model)
        {
            Category category = new Category();
            category.Name = model.Name;
            category.Description = model.Description;
           
            CategoriesService.Instance.SaveCategory(category);
            return RedirectToAction("Listing");
        }

        public ActionResult Edit(int ID)
        {
            CategoryViewModel model = new CategoryViewModel();
       
            var category = CategoriesService.Instance.CategoryGetById(ID);
            model.ID = category.ID;
            model.Name = category.Name;
          
            model.Description = category.Description;
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(CategoryViewModel model)
        {
            Category category =new Category();
            category.ID = model.ID;
            category.Name = model.Name;
            category.Description = category.Description;
            CategoriesService.Instance.UpdateCategory(category);
            return RedirectToAction("Listing");
         
        }

        public ActionResult Delete(int ID)
        {
            var model = CategoriesService.Instance.CategoryGetById(ID);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            CategoriesService.Instance.CategoryDelete(category);
            return RedirectToAction("Listing");
        }

        
        public ActionResult Details(int id)
        {
            CategoriesDetailViewModel model = new CategoriesDetailViewModel();
             model.Categories = CategoriesService.Instance.CategoryGetById(id);
            model.PageTitle = "Auction Detail" + model.Categories.Name;
            model.PageDescription = model.Categories.Description.Substring(0,10);

            return View(model);
        }
    }
}

DealDash.Web/Views/Categories/Create.cshtml
@model CategoryViewModel

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle">Create Record</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="createForm" method="post">
        <div class="form-group">
            <label>Name</label>
            <input class="form-control" name="Name" />
        </div>
        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="Description" />
        </div>

    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary" id="btnsave">Save changes</button>
</div>

<script>
    
    $("#btnsave").click(function () {
       
        $.ajax({
            url: '@Url.Action("Create", "Categories")',
            type: "post",
            data: $("#createForm").serialize()

        })
            .done(function (response) {
                $('#ShowHideModal').modal('toggle');
                $("#listingArea").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
</script>

DealDash.Web/Views/Categories/Details.cshtml
@model CategoriesDetailViewModel
<div class="row">

    <div class="col-lg-12">

        <div class="card mt-4">
           
            <div class="card-body">
                <h3 class="card-title">@Model.Categories.Name</h3>
                
                <p class="card-text">@Model.Categories.Description</p>
                <span class="text-warning">★ ★ ★ ★ ☆</span>
                4.0 stars
            </div>
        </div>
        <!-- /.card -->

        <div class="card card-outline-secondary my-4">
            <div class="card-header">
                Product Reviews
            </div>
            <div class="card-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <a href="#" class="btn btn-success">Leave a Review</a>
            </div>
        </div>
        <!-- /.card -->

    </div>
    <!-- /.col-lg-9 -->

</div>

DealDash.Web/Views/Categories/Edit.cshtml
@model CategoryViewModel
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle">Edit Record</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="editForm" method="post">
        <input class="form-control" name="ID" type="hidden" value="@Model.ID" />
        <div class="form-group">

            <label>Name</label>
            <input class="form-control" name="Name" value="@Model.Name" />
        </div>
        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="Description" value="@Model.Description" />
        </div>
       
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary" id="btnEdit">Save changes</button>
</div>
<script>
      
        $("#btnEdit").click(function () {
            
            $.ajax({
                url: '@Url.Action("Edit", "Categories")',
            method:"post",
            data: $("#editForm").serialize()

		})
            .done(function (response) {
                $('#ShowHideModal').modal('toggle');
                $("#listingArea").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
        });
        
</script>

DealDash.Web/Views/Categories/Index.cshtml
<div class="row">
    <div class="col-lg-12 m-2">
        <div>
            <button id="btnnew" class="btn btn-primary float-right"> New</button>
        </div>

        <div id="listingArea">
            @{Html.RenderAction("Listing");}
        </div>

        <!-- Modal -->
        <div class="modal fade" id="ShowHideModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" id="ModalContainer">

                </div>
            </div>
        </div>
       
        <script>

        $("#btnnew").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Categories")',
		})
                .done(function (response) {
                    $('#ShowHideModal').modal('toggle');
            $("#ModalContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
            });

        </script>
    </div>

</div>

DealDash.Web/Views/Categories/Listing.cshtml
@model CategoriesListingViewModel
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Name</th>
            
            <th>Description</th>
           
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var category in Model.Categories)
            {
            <tr>

                <td>
                    <input type="hidden" value="@category.ID" />
                    @category.Name
                </td>
                <td>@category.Description</td>
                <td>@category.Auctions.Count()</td>
                
                <td>
                    <button class="btnedit" data-id="@category.ID">Edit</button>
                    <button class="btndelete" data-id="@category.ID">Delete</button>
                </td>
            </tr>
        }

    </tbody>
</table>
<script>

    $(".btnedit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Categories")',
			data: {
                ID: $(this).attr("data-id")
			}
		})
            .done(function (response) {
                $('#ShowHideModal').modal('toggle');
                $("#ModalContainer").html(response);

        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
        $(".btndelete").click(function () {
            var result = confirm("Are Sure You want to delete this");

            if (result)
            {
                $.ajax({
                    url: '@Url.Action("Delete", "Categories")',
                    method:"post",
			data: {
                ID: $(this).attr("data-id")
			}
		})
                    .done(function (response) {

            $("#listingArea").html(response);

        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
            }

	});
</script>